### ISSUE TITLE
Mechanisms to maintain inventories

### ISSUE THREAD

**Issue by fedorov** [OSIPI/osipi.github.io#3]
Need to discuss what makes sense - ideas:
* shared google spreadsheet
  * pros: easy, integration with forms
  * cons: cumbersome to browse or format, limits to adding links, pictures, etc
* readthedocs documents (example: https://dicom4qi.readthedocs.io/)
  * pros: much nicer organization, easy access
  * cons: more difficult to edit content, has a (not so steep) learning curve

**Comment by notZaki** [comment]
Throwing another idea onto the pile:

- store data in JSON and render with html/javascript
    + pros: data is stored in plain text (json), making it easy to edit/update and it can be version-controlled
    + cons: requires someone comfortable with html/js to update the front-end

This is also similar to what [MR-Hub](https://ismrm.github.io/mrhub/) uses.

To get an idea of what this would look like, I grabbed the info from the [survey google sheet](https://docs.google.com/spreadsheets/d/1Zy3cnIBnBDoPtwM58iKijMVL0QhW1ogR0nshbLEsHls/) and the end result was the following two pages for:
   - [software packages](https://inventory.notzaki.com/packageinventory/) 
   - [data sources](https://inventory.notzaki.com/datainventory/)

The above pages were generated by [the source repository here](https://github.com/notZaki/perfusionInventory) while the [json files are located here](https://github.com/notZaki/inventory). Any changes to the json files (e.g. via pull request) will be automatically reflected on the website.
The json files probably contain incorrect information and most of the descriptions were copy/pasted from their respective website (this was just a test, after all).

**Comment by plaresmedima** [comment]
This looks great Zaki!

**Comment by fedorov** [comment]
Wow @notZaki - this is amazing! I love it, 110%! 👍 💯

**Comment by HenkMutsaerts** [comment]
Yes, this is a really nice idea! Still, if I would be to add information to this, I would probably add information in a GoogleSheet and convert this to the JSON format. I wrote some code for this, so we could use the multiple formats. For others it is probably easiest to input data into the GoogleSheet

**Comment by plaresmedima** [comment]
Hi @notZaki I have not forgotten about this! It looks amazing - we discussed this today on the executive board meeting as well. We are collecting quite a few resources now (https://www.osipi.org/resources/) so some sort of a more attractive front end would be great. How hard is this to do & customize & maintain? For those of us who are not wizards like you?

**Comment by notZaki** [comment]
For the front-end, the google docs/sheets would first have to be converted to `json` or `csv`---they're more convenient to work with. I think there might be an api that does this conversion, but I've never tried it.

The front-end in my example uses vue.js and the underlying code [looks like this](https://github.com/notZaki/perfusionInventory/blob/master/docs/.vuepress/components/dataInventory.vue). It's a bit hairy, but that's usually the nature of front-end.
However, that example was partially an excuse for me to try vuejs. There are many other options for how the front-end is implemented. Jekyll---which we are using for the website---can also be used. As mentioned earlier, this is what mr-hub uses. 

Ideally, the front-end should need minimal maintenance once it is set up. So it would be good to have a well thought-out vision of what the layout should be, what information should be shown, how it should be shown, what (if any) interactivity there ought to be, etc.

**Comment by plaresmedima** [comment]
Thanks Zaki - we'll look into it.

Prof. Steven Sourbron, PhD
Chair in Medical Imaging Physics
University of Sheffield, UK
*https
<https://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron>://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron
<https://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron>*
*Sheffield abdominal imaging research page*
<https://www.sheffield.ac.uk/medicine/research/research-themes/medical-imaging/medical-imaging-research/abdominal-imaging>
*Open source initiative in perfusion imaging* <http://www.osipi.org>
*Magnetic resonance imaging biomarkers for chronic kidney disease
<https://renalmri.org/>*

**Comment by HenkMutsaerts** [comment]
For task members it should be fine to use JSON, if they have an example. Reconsidering now the Google sheets, it might take a task member more time to check conversion, the specific nested JSON structure may not comply with the too free docs /sheets structure. On the other hand, the forms have a set structure, that should easily fit into a json. I'm adding @jan-petr to this discussion, he and Sudipto are leading the ASL pipeline inventory and could code this easily, or at least give feedback as inventory creator.

Perhaps we should also collect feedback from the other inventory leads?

**Comment by petravanhoudt** [comment]
closed this issue as the website is currently not being maintained anymore due to the move to the ISMRM domain
