### ISSUE TITLE
Remove New Blog Articles from home page

### ISSUE THREAD

**Issue by plaresmedima** [OSIPI/osipi.github.io#37]
I wanted to remove the links to New blog articles from the home page. They are not new and anyway they can be foudn directly via the News link at the top. I can't seem to find where this link is made though - can someone help?

**Comment by notZaki** [comment]
Deleting the following section should get rid of the blog/news.

https://github.com/OSIPI/osipi.github.io/blob/bea131f14f7ae20cea48a3ad79c654da48815233/_layouts/frontpage.html#L66-L112
