### ISSUE TITLE
Editing task force pages

### ISSUE THREAD

**Issue by plaresmedima** [OSIPI/osipi.github.io#44]
Currently task force leads need two links to edit their page, one to the yml file in case they want ro edit the fact sheet, and one to the .md file in case they want to add free text. Can this be combined so they need to edit in one place only?

**Comment by notZaki** [comment]
The .md file starts with a yml section, so we can just move everything from the .yml files into the respective .md file.

It'll require a few more changes to the backend. I'll try playing with this tomorrow.
