### ISSUE TITLE
Shape of the headshot is different across pages

### ISSUE THREAD

**Issue by fedorov** [OSIPI/osipi.github.io#48]
It's not a huge deal, but I find it rather idiosyncratic and not very professional to have differences in styling of the headshot - sometimes those are round, sometimes ellipsoid with different aspect ratios. Is this intentional, or just because fixing it is not straightforward?

**Comment by notZaki** [comment]
The shape is based on the photo's aspect ratio, i.e. a square photo will become a circle while a rectangular one becomes an ellipsoid.
One way to fix the shapes would be to use a consistent aspect ratio for all the images in [`assets/img/headshots/`](https://github.com/OSIPI/osipi.github.io/tree/1f49b9c55375cf3a1f08ef982fedb90784706809/assets/img/headshots), e.g. crop them to 1:1 aspect ratio

**Comment by fedorov** [comment]
Thanks Zaki, makes sense. IMHO, this would be good to fix, if everyone agrees, but not a high priority of course.

**Comment by plaresmedima** [comment]
It's been irritating me a little as well but have not had a chance to fix
it ;-)

-----------------------------------------------------------------------------------
Steven Sourbron
Chair in Medical Imaging Physics
Department of Infection, Immunity and Cardiovascular Disease
University of Sheffield
-----------------------------------------------------------------------------------

**Comment by Aditish51** [comment]
Hello, This is Aditi .Can I give this issue a try? I  just need to fix the aspect ratio for the images located in `assets/img/headshots/.`

**Comment by petravanhoudt** [comment]
Hi @Aditish51 thank you for your offered help, however, we are not maintaining this website anymore as we are transitioning to a different domain.
