### ISSUE TITLE
News page only showing last 5 entries

### ISSUE THREAD

**Issue by plaresmedima** [OSIPI/osipi.github.io#83]
Can we change this so that the news simply shows one long list of items? The last one is always on top anyway so it's Ok to have a long list below. Makes it easier to scroll through.

Sorry but I don't know how!

**Comment by notZaki** [comment]
I believe it's this configuration line:
https://github.com/OSIPI/osipi.github.io/blob/efc0f9df010d1080b8140c50494a7586e0e1bae0/_config.yml#L61

Setting it to a larger value should do the trick.

**Comment by plaresmedima** [comment]
That has done the trick, thanks!!
